### ISSUE TITLE
Sample code for using the framework

### ISSUE THREAD

**Issue by amalcty** [swittk/MediapipeFaceMeshIOSLibrary#1]
Can you please provide sample code for using the framework in an app to get facial landmarks from an image or video stream ?

**Comment by krishnanmuthiahpillai** [comment]
@amalcty https://github.com/krishnanmuthiahpillai/DemoAppForMediaPipe

**Comment by krishnanmuthiahpillai** [comment]
@amalcty please find sample app for mediapipe facemesh with the help of pod file.
https://github.com/krishnanmuthiahpillai/DemoAppForMediaPipe
