### ISSUE TITLE
I got Error: 'apple_common' value has no field or method 'objc_proto_aspect' when install with ./BUILD_FACE_MESH_XCFRAMEWORK.sh

### ISSUE THREAD

**Issue by cube76** [swittk/MediapipeFaceMeshIOSLibrary#3]
when I install it with ./BUILD_FACE_MESH_XCFRAMEWORK.sh I got error like below

`ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_tryanadityaputra/3f1a92394fe1d14256beb1af178a8a06/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 62, column 61, in <toplevel>
		ios_ui_test_bundle = rule_factory.create_apple_bundling_rule(
	File "/private/var/tmp/_bazel_tryanadityaputra/3f1a92394fe1d14256beb1af178a8a06/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
		rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
	File "/private/var/tmp/_bazel_tryanadityaputra/3f1a92394fe1d14256beb1af178a8a06/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
		apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Skipping 'mediapipe/examples/ios/facemeshioslib:FaceMeshIOSLibFramework': error loading package 'mediapipe/examples/ios/facemeshioslib': at /private/var/tmp/_bazel_tryanadityaputra/3f1a92394fe1d14256beb1af178a8a06/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed
WARNING: Target pattern parsing failed.
ERROR: error loading package 'mediapipe/examples/ios/facemeshioslib': at /private/var/tmp/_bazel_tryanadityaputra/3f1a92394fe1d14256beb1af178a8a06/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed
INFO: Elapsed time: 1.818s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: mediapipe/examples/ios/facemeshioslib
tryanadityaputra@tryans-MacBook-Air MediapipeFaceMeshIOSLibrary % bazel build --copt=-fembed-bitcode --apple_bitcode=embedded --config=ios_arm64 mediapipe/examples/ios/facemeshioslib:FaceMeshIOSLibFramework`

I already tried to upgrade bazel but seems no different. Is there anything I should do or it just deprecated?

**Comment by lxm1799** [comment]
download his release zip :https://github.com/swittk/MediapipeFaceMeshIOSLibrary/releases

**Comment by swittk** [comment]
This was (and is) only an example for others to try implement; not as something to be used in production.
Regarding this issue, maybe there are breaking changes in Bazel? I really have no idea since I haven't had the time to experiment with things (at least until I finish my residency training).
