### ISSUE TITLE
Is it possible to build the framework for macOS instead of iOS?

### ISSUE THREAD

**Issue by peymanbateni** [swittk/MediapipeFaceMeshIOSLibrary#5]
Is it possible to build the framework for macOS instead of iOS? If so, can you please provide some guidance? Thank you so much!!!

**Comment by swittk** [comment]
I'm just speculating, but I think you can do that by tweaking the framework build phase.
But sorry, I really can't provide guidance on this since I'd need time to experiment with it.
If you do find that it's possible, then PRs are welcome.
